name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set environments
        run: |
          {
            echo "version=v$(grep versionName ctz/build.gradle | awk -F\" '{print $2}')"
            echo "commit=$(echo ${{ github.sha }} | cut -c-7)"
            echo "repo=$(echo ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/})"
          } >> $GITHUB_ENV

      - name: Build
        run: |
          ./gradlew --no-daemon --warning-mode=all assembleDebug
          cp -f ct3/build/outputs/apk/debug/ct3-debug.apk ${{ env.repo }}-${{ env.version }}@${{ env.commit }}-CT3.apk
          cp -f ctz/build/outputs/apk/debug/ctz-debug.apk ${{ env.repo }}-${{ env.version }}@${{ env.commit }}-CTZ.apk

      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: ${{ env.repo }}-${{ env.version }}@${{ env.commit }}-CT?.apk

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.repo }}-${{ env.version }}@${{ env.commit }}
          path: ${{ env.repo }}-${{ env.version }}@${{ env.commit }}-CT?.apk
